<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBrADfe1\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBrADfe1/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBrADfe1.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBrADfe1\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerBrADfe1\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'BrADfe1',
    'container.build_id' => 'f6eacb81',
    'container.build_time' => 1569898072,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBrADfe1');
