<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKkG1ubl\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKkG1ubl/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKkG1ubl.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKkG1ubl\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerKkG1ubl\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'KkG1ubl',
    'container.build_id' => '7f8e4867',
    'container.build_time' => 1569374058,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKkG1ubl');
