<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerApPfDuB\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerApPfDuB/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerApPfDuB.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerApPfDuB\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerApPfDuB\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'ApPfDuB',
    'container.build_id' => 'c24d2a23',
    'container.build_time' => 1569549936,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerApPfDuB');
